# Default Configuration for DNA Condensation Quantification
# This file contains default values - copy to config.yaml and modify as needed

# ==== FILE PATHS ====
# REQUIRED: Set the path to your ND2 files
raw_nd2_path: null              # Path to folder containing ND2 files
output_path: "./output"         # Where to save results
temp_path: "./temp"             # Temporary processing files

# ==== MICROSCOPE SETTINGS ====
# Adjust these based on your microscope configuration
image_channels:
  - "Channel_0"    # LSD1 GFP channel
  - "Channel_1"    # DNA staining channel

# ==== SEGMENTATION SETTINGS ====
# Channel selection for nucleus segmentation
segmentation_channel_index: 1   # index to use for quantification (1 = DNA staining channel) 
# Segmentation method: 'yolo' (AI-based) or 'watershed' (traditional image processing)
segmentation_method: "otsu"    # Options: "yolo", "watershed" 

# Size-based filtering (removes small objects relative to median size)
size_filtering:
  enabled: true                 # Enable/disable size-based filtering
  min_size_percentage: 20       # Minimum size as percentage of median (e.g., 20 = 20% of median) 

#=== SIZE FILTERING SUMMARY EXAMPLE ===
# Original objects: 66
#  5% filter:  66 objects (  0.0% removed)
# 10% filter:  66 objects (  0.0% removed)
# 20% filter:  64 objects (  3.0% removed)
# 30% filter:  62 objects (  6.1% removed)

# ==== PROCESSING SETTINGS ====
# Preprocessing options for homogeneity analysis
preprocessing:
  background_correction: true   # Apply rolling ball background correction (RECOMMENDED)
  deconvolution: false         # Apply Richardson-Lucy deconvolution (optional, slower)
  intensity_normalization: true # Apply global intensity normalization (recommended for batch comparison)
  per_nucleus_normalization: true  # Apply per-nucleus normalization for homogeneity analysis
  # Advanced parameters
  bg_ball_radius: 50           # Rolling ball radius (adjust based on nucleus size)
  deconv_iterations: 10        # Deconvolution iterations
  norm_method: "percentile"    # Normalization method: percentile, zscore, minmax, target_mean

# Z-axis collapse method
z_collapse_method: "mean"       # Options: "max", "mean", "sum", "median"

# GPU acceleration
use_gpu: true                   # Enable GPU acceleration if available

# Plotting and visualization
plot:
  plot_segmentation: true       # Enable/disable segmentation result visualization

# Verbose output
verbose: true                   # Print detailed progress information
