# Development-specific overrides.
# Settings in this file will replace values from config.yaml when dev_mode is true.

# Development-specific overrides for faster execution.
# These settings will be used if `dev_mode: true` is set in the main config.yaml.

# 1. Process a minimal number of images to speed up I/O and processing loops.
nd2_selection_settings:
  count: 6  # Process less ND2 files to speed up analysis.

bbbc022_settings:
  count: 6 # Process less ND2 files to speed up analysis.

# 2. Disable computationally expensive preprocessing steps.
preprocessing:
  background_correction: false   # Apply rolling ball background correction (RECOMMENDED)
  bg_ball_radius: 150           # Smaller values will run faster, but nuclear detail will be lost.

  deconvolution: false         # Apply Richardson-Lucy deconvolution (optional, slower, disabled because it may interfere with analysis)
  deconv_iterations: 10        # Deconvolution iterations

  intensity_normalization: true # Apply global intensity normalization (recommended for batch comparison)
  norm_method: "percentile"    # Normalization method: percentile, zscore, minmax, target_mean

  per_nucleus_normalization: true  # Apply per-nucleus normalization for homogeneity analysis

# 3. Use the fastest available segmentation method.
segmentation_method: "stardist" # Otsu is much faster than watershed or other complex methods.

# 4. Disable all plotting to prevent blocking execution for visualization.
plot:
  plot_segmentation: false
  single_metric_plot:
    enabled: true
